
import com.sun.glass.ui.Cursor;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author renuka
 */
public
        class welcome extends javax.swing.JFrame
  {

   

    /**
     * Creates new form welcome
     */
    public
            welcome ()
    {
        initComponents ();
        setIcon();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        progressbar = new javax.swing.JProgressBar();
        value = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1620, 900));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 930, 710, 30));

        value.setBackground(new java.awt.Color(204, 204, 255));
        value.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        value.setForeground(new java.awt.Color(255, 255, 255));
        value.setText("0%");
        getContentPane().add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 920, 80, 40));

        label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("loading...");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 970, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (176).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jLabel1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jLabel1KeyPressed
    {//GEN-HEADEREND:event_jLabel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseClicked
    {//GEN-HEADEREND:event_jLabel1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main ( String args[] )
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels () )
            {
                if ( "Nimbus".equals ( info.getName () ) )
                {
                    javax.swing.UIManager.setLookAndFeel ( info.getClassName () );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger ( welcome.class.getName () ).log ( java.util.logging.Level.SEVERE , null , ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger ( welcome.class.getName () ).log ( java.util.logging.Level.SEVERE , null , ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger ( welcome.class.getName () ).log ( java.util.logging.Level.SEVERE , null , ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger ( welcome.class.getName () ).log ( java.util.logging.Level.SEVERE , null , ex );
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
         welcome pb=new welcome ();
       pb.setVisible ( true );
        try
        {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep ( 100);
                pb.value.setText (i+"%");

                if(i==10)
                {
                   pb.progressbar.setValue ( i );
                   pb.label.setText ( "Turning on Modules.....");
                }

                if(i==30)
                {
                  pb.progressbar.setValue ( i );
                  pb.label.setText ( "Loading Modules.....");
                }

                if(i==50)
                {
                  pb.progressbar.setValue ( i );
                  pb.label.setText ( "Connectiong to Database.....");
                }

                if(i==70)
                {
                    pb.progressbar.setValue ( i );
                    pb.label.setText ( "Successfully Connected.....");
                }

                if(i==90)
                {
                  pb.progressbar.setValue ( i );
                  pb.label.setText ( "Launching Application.....");
                }
               if(i==100)
              {
                       pb.progressbar.setValue ( i ); 
                       new signinup ().setVisible ( true );
                   }
 }
      
        }
        catch ( InterruptedException e )
        {
            JOptionPane.showMessageDialog ( null, e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables

    private
    void setIcon ()
    {
        setIconImage ( Toolkit.getDefaultToolkit ().getImage ( getClass ().getResource ( "red-cross.png")));
    }
  }
